#!/bin/sh

. "/omd/sites/ow_monitor/.profile"

export PHP_FCGI_MAX_REQUESTS=1000

# Replace with the path to your FastCGI-enabled PHP executable
exec /usr/bin/php-cgi \
    -d session.save_handler=files \
    -d session.save_path=/omd/sites/ow_monitor/tmp/php/session \
    -d upload_tmp_dir=/omd/sites/ow_monitor/tmp/php/upload \
    -d soap.wsdl_cache_dir=/omd/sites/ow_monitor/tmp/php/wsdl-cache \
    -d safe_mode='Off' \
    -d mysql.default_socket=/omd/sites/ow_monitor/tmp/run/mysqld/mysqld.sock
