# Written by Multisite UserDB
# encoding: utf-8

multisite_users = \
{u'craig.rose': {'alias': u'Craig Rose',
                 'connector': 'ldap',
                 'language': None,
                 'roles': ['user']},
 u'daz': {'alias': u'Darren Furlotte',
          'connector': 'ldap',
          'force_authuser': False,
          'force_authuser_webservice': False,
          'language': None,
          'locked': False,
          'roles': ['user']},
 u'haydn.cahir': {'alias': u'Haydn Cahir',
                  'connector': 'ldap',
                  'language': None,
                  'roles': ['user']},
 u'leigh.mason': {'alias': u'Leigh Mason',
                  'connector': 'ldap',
                  'language': None,
                  'roles': ['user']},
 u'maani.g': {'alias': u'Maani G',
              'connector': 'ldap',
              'language': None,
              'roles': ['user']},
 'omdadmin': {'alias': 'omdadmin',
              'language': None,
              'locked': False,
              'roles': ['admin']},
 u'paul.singh': {'alias': u'Paul Singh',
                 'connector': 'ldap',
                 'language': None,
                 'roles': ['user']},
 u'temp.user': {'alias': u'Temp User',
                'connector': 'ldap',
                'language': None,
                'roles': ['user']}}
