; <?php exit(1); ?>
; Do not edit this file. Your changes will be overwritten.
; This file is controlled by the OMD hook NAGVIS_URLS.
;
; Written by OMD hook NAGVIS_URLS at Tue May 12 17:03:39 AEST 2015.
[paths]
htmlcgi="/idaas/welcome/cgi-bin"

[defaults]
hosturl="[htmlcgi]/status.cgi?host=[host_name]"
hostgroupurl="[htmlcgi]/status.cgi?hostgroup=[hostgroup_name]"
serviceurl="[htmlcgi]/extinfo.cgi?type=2&host=[host_name]&service=[service_description]"
servicegroupurl="[htmlcgi]/status.cgi?servicegroup=[servicegroup_name]&style=detail"
