# Written by Multisite UserDB
# encoding: utf-8

contacts.update(
{'andrew.horne': {'alias': u'Andrew',
                  'contactgroups': [],
                  'email': 'andrew.horne@openwindows.com.au',
                  'host_notification_options': 'durfs',
                  'notification_method': 'email',
                  'notification_period': '24X7',
                  'notifications_enabled': False,
                  'pager': '',
                  'service_notification_options': 'wucrfs'},
 u'craig.rose': {'alias': u'Craig Rose',
                 'contactgroups': ['grp_IDaaS'],
                 'email': u'craig.rose@openwindows.com.au',
                 'host_notification_options': 'durfs',
                 'notification_method': 'email',
                 'notification_period': '24X7',
                 'notifications_enabled': False,
                 'pager': '',
                 'service_notification_options': 'wucrfs'},
 'darren': {'alias': u'Darren Furlotte',
            'contactgroups': ['all'],
            'email': 'darren.furlotte@openwindows.com.au',
            'host_notification_options': '',
            'notification_method': ('flexible',
                                    [{'disabled': False,
                                      'host_events': ['d', 'u', 'r', 'x'],
                                      'parameters': [],
                                      'plugin': 'mail',
                                      'service_events': ['c', 'r', 'x'],
                                      'timeperiod': 'AEST_BH'}]),
            'notification_period': 'AEST_BH',
            'notifications_enabled': True,
            'pager': 'omdadmin',
            'service_notification_options': ''},
 u'daz': {'alias': u'Darren Furlotte',
          'email': u'darren.furlotte@openwindows.com.au'},
 u'haydn.cahir': {'alias': u'Haydn Cahir',
                  'contactgroups': ['grp_IDaaS'],
                  'email': u'haydn.cahir@openwindows.com.au',
                  'host_notification_options': 'durfs',
                  'notification_method': 'email',
                  'notification_period': '24X7',
                  'notifications_enabled': False,
                  'pager': '',
                  'service_notification_options': 'wucrfs'},
 u'leigh.mason': {'alias': u'Leigh Mason',
                  'contactgroups': ['grp_IDaaS'],
                  'email': u'leigh.mason@openwindows.com.au',
                  'host_notification_options': 'durfs',
                  'notification_method': 'email',
                  'notification_period': '24X7',
                  'notifications_enabled': False,
                  'pager': '',
                  'service_notification_options': 'wucrfs'},
 u'maani.g': {'alias': u'Maani G'},
 'omdadmin': {'alias': u'omdadmin',
              'contactgroups': [],
              'email': '',
              'host_notification_options': 'dr',
              'notification_method': 'email',
              'notification_period': '24X7',
              'notifications_enabled': False,
              'pager': '',
              'service_notification_options': 'crs'},
 u'paul.singh': {'alias': u'Paul Singh',
                 'email': u'paul.singh@openwindows.com.au'},
 'rob': {'alias': u'Rob Canterbury',
         'contactgroups': ['AHChangeOver', 'Z_DriveDelete'],
         'email': 'rob.canterbury@openwindows.com.au',
         'host_notification_options': '',
         'notification_method': ('flexible',
                                 [{'disabled': False,
                                   'host_events': [],
                                   'only_services': ['AHscript_error'],
                                   'parameters': [],
                                   'plugin': 'mail',
                                   'service_events': ['c', 'r'],
                                   'timeperiod': '24X7'}]),
         'notification_period': 'AEST_BH',
         'notifications_enabled': True,
         'pager': 'omdadmin',
         'service_notification_options': 'cr'},
 'russell': {'alias': u'Russell Doig',
             'contactgroups': [],
             'email': 'russell@openwindows.com.au',
             'host_notification_options': 'durfs',
             'notification_method': 'email',
             'notification_period': '24X7',
             'notifications_enabled': False,
             'pager': '',
             'service_notification_options': 'wucrfs'},
 u'temp.user': {'alias': u'Temp User'}}
)
