# Written by WATO
# encoding: utf-8


host_contactgroups += [
    ( 'all', ['192.168.1.35'] ),
]


host_contactgroups += [
    ( 'all', ['AUDB1'] ),
]


host_contactgroups += [
    ( 'all', ['Internal'] ),
]


host_contactgroups += [
    ( 'all', ['JSS-02'] ),
]


host_contactgroups += [
    ( 'all', ['OW-SPS-01'] ),
]


host_contactgroups += [
    ( 'all', ['OW-SPS-02'] ),
]


host_contactgroups += [
    ( 'all', ['Webservices'] ),
]

all_hosts += [
  "192.168.1.35|snmp-only|critical|snmp|lan|WINsrv|wato|/" + FOLDER_PATH + "/",
  "AP1|lan|wifi-01|cmk-agent|snmp|tcp|WINsrv|prod|wato|/" + FOLDER_PATH + "/",
  "AP2|lan|wifi-01|cmk-agent|snmp|tcp|WINsrv|prod|wato|/" + FOLDER_PATH + "/",
  "AP3|lan|wifi-01|cmk-agent|snmp|tcp|WINsrv|prod|wato|/" + FOLDER_PATH + "/",
  "AUDB1|LinuxSRV|cmk-agent|prod|lan|tcp|wato|/" + FOLDER_PATH + "/",
  "HelpDeskPilot|cmk-agent|prod|lan|tcp|WINsrv|wato|/" + FOLDER_PATH + "/",
  "Internal|cmk-agent|prod|lan|tcp|WINsrv|wato|/" + FOLDER_PATH + "/",
  "JSS-02|cmk-agent|prod|lan|tcp|WINsrv|wato|/" + FOLDER_PATH + "/",
  "OW-ADS-01|cmk-agent|prod|lan|tcp|WINsrv|wato|/" + FOLDER_PATH + "/",
  "OW-ADS-02|cmk-agent|prod|lan|tcp|WINsrv|wato|/" + FOLDER_PATH + "/",
  "OW-ADS-03|cmk-agent|prod|lan|tcp|WINsrv|wato|/" + FOLDER_PATH + "/",
  "OW-FSS-01|cmk-agent|prod|lan|tcp|WINsrv|wato|/" + FOLDER_PATH + "/",
  "OW-OBJ-01|cmk-agent|prod|lan|tcp|WINsrv|wato|/" + FOLDER_PATH + "/",
  "OW-SPS-01|cmk-agent|prod|lan|tcp|WINsrv|wato|/" + FOLDER_PATH + "/",
  "OW-SPS-02|cmk-agent|prod|lan|tcp|WINsrv|wato|/" + FOLDER_PATH + "/",
  "OW-SQL-01|cmk-agent|prod|lan|tcp|WINsrv|wato|/" + FOLDER_PATH + "/",
  "Quinby|cmk-agent|prod|lan|tcp|WINsrv|wato|/" + FOLDER_PATH + "/",
  "SugarCRM|cmk-agent|prod|lan|tcp|WINsrv|wato|/" + FOLDER_PATH + "/",
  "Support|cmk-agent|prod|lan|tcp|WINsrv|wato|/" + FOLDER_PATH + "/",
  "Switch_PoE|snmp-only|prod|snmp|lan|WINsrv|wato|/" + FOLDER_PATH + "/",
  "TFSBuild|cmk-agent|prod|lan|tcp|WINsrv|wato|/" + FOLDER_PATH + "/",
  "Webservices|cmk-agent|prod|lan|tcp|WINsrv|wato|/" + FOLDER_PATH + "/",
  "WiFiController|lan|wifi-01|snmp|WINsrv|snmp-only|prod|wato|/" + FOLDER_PATH + "/",
  "ow-exch-01|wan|cmk-agent|prod|tcp|WINsrv|wato|/" + FOLDER_PATH + "/",
  "ow-tfs|cmk-agent|prod|lan|tcp|WINsrv|wato|/" + FOLDER_PATH + "/",
]

# Explicit IP addresses
ipaddresses.update({'192.168.1.35': u'192.168.1.35',
 'AP1': u'192.168.1.32',
 'AP2': u'192.168.1.33',
 'AP3': u'192.168.1.34',
 'AUDB1': u'192.168.1.127',
 'HelpDeskPilot': u'192.168.1.12',
 'Internal': u'192.168.1.131',
 'JSS-02': u'192.168.1.64',
 'OW-ADS-01': u'192.168.1.4',
 'OW-ADS-02': u'192.168.1.6',
 'OW-ADS-03': u'172.26.54.110',
 'OW-FSS-01': u'192.168.1.100',
 'OW-OBJ-01': u'192.168.1.26',
 'OW-SPS-01': u'192.168.1.13',
 'OW-SPS-02': u'192.168.1.56',
 'OW-SQL-01': u'192.168.1.16',
 'Quinby': u'192.168.1.80',
 'SugarCRM': u'192.168.1.19',
 'Support': u'192.168.1.78',
 'Switch_PoE': u'192.168.1.30',
 'TFSBuild': u'192.168.1.69',
 'Webservices': u'192.168.1.11',
 'WiFiController': u'192.168.1.31',
 'ow-exch-01': u'172.26.54.100',
 'ow-tfs': u'192.168.1.75'})

# Explicit SNMP communities
explicit_snmp_communities.update({'192.168.1.35': u'ow_mon',
 'Switch_PoE': u'public',
 'WiFiController': u'private'})

# Settings for alias
extra_host_conf.setdefault('alias', []).extend(
  [(u'ServiceDeskApp_IP12', ['HelpDeskPilot']),
 (u'192.168.1.80', ['Quinby']),
 (u'DnStairsPoE', ['192.168.1.35']),
 (u'VeeamBkUp_IP16', ['OW-SQL-01']),
 (u'172.26.54.100', ['ow-exch-01']),
 (u'Top Floor AP', ['AP2']),
 (u'Dev Office', ['AP3']),
 (u'SalesCRM_IP19', ['SugarCRM']),
 (u'Admin Office AP', ['AP1']),
 (u'FileSever_IP100', ['OW-FSS-01']),
 (u'PrimaryActiveDir_192.168.1.4', ['OW-ADS-01']),
 (u'SecActiveDir_192.168.1.6', ['OW-ADS-02']),
 (u'TertiaryActiveDir_172.26.54.110', ['OW-ADS-03']),
 (u'IntContractApp_IP131', ['Internal']),
 (u'SharePoint_IP13', ['OW-SPS-01']),
 (u'DevTeamFound_IP69', ['TFSBuild']),
 (u'eValuaSRV: 1.127', ['AUDB1']),
 (u'JobSevice_192.168.1.64', ['JSS-02'])])

# Settings for parents
extra_host_conf.setdefault('parents', []).extend(
  [('ANNETTE', ['HelpDeskPilot']),
 ('ANNETTE', ['ow-tfs']),
 ('MANJULA', ['OW-OBJ-01']),
 ('WiFiController', ['AP2']),
 ('WiFiController', ['AP3']),
 ('APU', ['SugarCRM']),
 ('WiFiController', ['AP1']),
 ('ANNETTE', ['OW-SPS-02']),
 ('APU', ['OW-FSS-01']),
 ('gw-172-31-172-93', ['ow-exch-01']),
 ('gw-172-31-172-93', ['OW-ADS-03']),
 ('APU', ['Internal']),
 ('APU', ['OW-SPS-01']),
 ('MANJULA', ['TFSBuild']),
 ('HOMER', ['Support']),
 ('APU', ['Webservices'])])

# Host attributes (needed for WATO)
host_attributes.update(
{'192.168.1.35': {'alias': u'DnStairsPoE',
                  'contactgroups': (True, ['all']),
                  'ipaddress': u'192.168.1.35',
                  'snmp_community': u'ow_mon',
                  'tag_agent': 'snmp-only',
                  'tag_criticality': 'critical'},
 'AP1': {'alias': u'Admin Office AP',
         'inventory_failed': True,
         'ipaddress': u'192.168.1.32',
         'parents': ['WiFiController'],
         'tag_WiFi': 'wifi-01',
         'tag_agent': 'cmk-agent'},
 'AP2': {'alias': u'Top Floor AP',
         'inventory_failed': True,
         'ipaddress': u'192.168.1.33',
         'parents': ['WiFiController'],
         'tag_WiFi': 'wifi-01',
         'tag_agent': 'cmk-agent'},
 'AP3': {'alias': u'Dev Office',
         'inventory_failed': True,
         'ipaddress': u'192.168.1.34',
         'parents': ['WiFiController'],
         'tag_WiFi': 'wifi-01',
         'tag_agent': 'cmk-agent'},
 'AUDB1': {'alias': u'eValuaSRV: 1.127',
           'contactgroups': (True, ['all']),
           'ipaddress': u'192.168.1.127',
           'tag_OS': 'LinuxSRV'},
 'HelpDeskPilot': {'alias': u'ServiceDeskApp_IP12',
                   'inventory_failed': True,
                   'ipaddress': u'192.168.1.12',
                   'parents': ['ANNETTE']},
 'Internal': {'alias': u'IntContractApp_IP131',
              'contactgroups': (True, ['all']),
              'ipaddress': u'192.168.1.131',
              'parents': ['APU'],
              'tag_OS': 'WINsrv',
              'tag_agent': 'cmk-agent',
              'tag_criticality': 'prod',
              'tag_networking': 'lan'},
 'JSS-02': {'alias': u'JobSevice_192.168.1.64',
            'contactgroups': (True, ['all']),
            'ipaddress': u'192.168.1.64',
            'tag_OS': 'WINsrv'},
 'OW-ADS-01': {'alias': u'PrimaryActiveDir_192.168.1.4',
               'ipaddress': u'192.168.1.4',
               'tag_agent': 'cmk-agent'},
 'OW-ADS-02': {'alias': u'SecActiveDir_192.168.1.6',
               'ipaddress': u'192.168.1.6'},
 'OW-ADS-03': {'alias': u'TertiaryActiveDir_172.26.54.110',
               'ipaddress': u'172.26.54.110',
               'parents': ['gw-172-31-172-93'],
               'tag_OS': 'WINsrv',
               'tag_agent': 'cmk-agent',
               'tag_criticality': 'prod',
               'tag_networking': 'lan'},
 'OW-FSS-01': {'alias': u'FileSever_IP100',
               'ipaddress': u'192.168.1.100',
               'parents': ['APU']},
 'OW-OBJ-01': {'ipaddress': u'192.168.1.26',
               'parents': ['MANJULA'],
               'tag_agent': 'cmk-agent'},
 'OW-SPS-01': {'alias': u'SharePoint_IP13',
               'contactgroups': (True, ['all']),
               'ipaddress': u'192.168.1.13',
               'parents': ['APU'],
               'tag_agent': 'cmk-agent',
               'tag_criticality': 'prod',
               'tag_networking': 'lan'},
 'OW-SPS-02': {'contactgroups': (True, ['all']),
               'ipaddress': u'192.168.1.56',
               'parents': ['ANNETTE'],
               'tag_agent': 'cmk-agent',
               'tag_criticality': 'prod',
               'tag_networking': 'lan'},
 'OW-SQL-01': {'alias': u'VeeamBkUp_IP16',
               'ipaddress': u'192.168.1.16',
               'tag_agent': 'cmk-agent',
               'tag_criticality': 'prod',
               'tag_networking': 'lan'},
 'Quinby': {'alias': u'192.168.1.80',
            'ipaddress': u'192.168.1.80',
            'tag_OS': 'WINsrv',
            'tag_agent': 'cmk-agent'},
 'SugarCRM': {'alias': u'SalesCRM_IP19',
              'ipaddress': u'192.168.1.19',
              'parents': ['APU'],
              'tag_agent': 'cmk-agent',
              'tag_criticality': 'prod',
              'tag_networking': 'lan'},
 'Support': {'ipaddress': u'192.168.1.78',
             'parents': ['HOMER'],
             'tag_agent': 'cmk-agent',
             'tag_criticality': 'prod'},
 'Switch_PoE': {'ipaddress': u'192.168.1.30',
                'snmp_community': u'public',
                'tag_agent': 'snmp-only'},
 'TFSBuild': {'alias': u'DevTeamFound_IP69',
              'ipaddress': u'192.168.1.69',
              'parents': ['MANJULA'],
              'tag_agent': 'cmk-agent',
              'tag_criticality': 'prod',
              'tag_networking': 'lan'},
 'Webservices': {'contactgroups': (True, ['all']),
                 'ipaddress': u'192.168.1.11',
                 'parents': ['APU'],
                 'tag_agent': 'cmk-agent',
                 'tag_criticality': 'prod',
                 'tag_networking': 'lan'},
 'WiFiController': {'ipaddress': u'192.168.1.31',
                    'snmp_community': u'private',
                    'tag_WiFi': 'wifi-01',
                    'tag_agent': 'snmp-only',
                    'tag_criticality': 'prod'},
 'ow-exch-01': {'alias': u'172.26.54.100',
                'ipaddress': u'172.26.54.100',
                'parents': ['gw-172-31-172-93'],
                'tag_agent': 'cmk-agent',
                'tag_criticality': 'prod',
                'tag_networking': 'wan'},
 'ow-tfs': {'contactgroups': (True, []),
            'ipaddress': u'192.168.1.75',
            'parents': ['ANNETTE'],
            'tag_agent': 'cmk-agent',
            'tag_criticality': 'prod',
            'tag_networking': 'lan'}})
