# Written by WATO
# encoding: utf-8

roles.update(
{'admin': {'alias': 'Administrator', 'builtin': True, 'permissions': {}},
 'guest': {'alias': 'Guest user', 'builtin': True, 'permissions': {}},
 'user': {'alias': u'Normal monitoring user',
          'builtin': True,
          'permissions': {'action.customnotification': False,
                          'action.downtimes': False,
                          'action.reschedule': False,
                          'general.act': False,
                          'general.change_password': False,
                          'general.edit_notifications': False,
                          'general.edit_profile': False,
                          'general.edit_user_attributes': False,
                          'general.see_all': False,
                          'general.view_option_columns': False,
                          'nagvis.*_*_*': True,
                          'nagvis.Map_view_*': True,
                          'nagvis.Rotation_view_*': True,
                          'sidesnap.about': False,
                          'sidesnap.admin': False,
                          'sidesnap.admin_mini': False,
                          'sidesnap.custom_links': False,
                          'sidesnap.master_control': False,
                          'sidesnap.nagios_legacy': False,
                          'sidesnap.nagvis_maps': False,
                          'sidesnap.tactical_overview': False,
                          'sidesnap.wato_folders': False,
                          'sidesnap.wato_foldertree': False,
                          'sidesnap.wiki': False,
                          'view.aggr_host': False,
                          'view.aggr_hostnameaggrs': False,
                          'view.aggr_problems': False,
                          'view.aggr_single': False,
                          'view.aggr_singlehost': False,
                          'view.aggr_singlehosts': False,
                          'view.aggr_summary': False,
                          'view.mobile_notifications': False,
                          'wato.edit': False,
                          'wato.use': False}}})
