# Written by Multisite UserDB
# encoding: utf-8

multisite_users = \
{'andrew.horne': {'alias': u'Andrew',
                  'force_authuser': False,
                  'force_authuser_webservice': False,
                  'language': None,
                  'locked': False,
                  'roles': ['user']},
 u'craig.rose': {'alias': u'Craig Rose',
                 'connector': 'ldap',
                 'force_authuser': True,
                 'force_authuser_webservice': True,
                 'language': None,
                 'ldap_pw_last_changed': u'130753799588908837',
                 'locked': False,
                 'roles': ['user']},
 'darren': {'alias': u'Darren Furlotte',
            'force_authuser': False,
            'force_authuser_webservice': False,
            'language': None,
            'locked': False,
            'roles': ['admin']},
 u'daz': {'alias': u'Darren Furlotte',
          'connector': 'ldap',
          'ldap_pw_last_changed': u'130737017657829030',
          'roles': ['user']},
 u'haydn.cahir': {'alias': u'Haydn Cahir',
                  'connector': 'ldap',
                  'force_authuser': True,
                  'force_authuser_webservice': True,
                  'language': None,
                  'ldap_pw_last_changed': u'130737105911875037',
                  'locked': False,
                  'roles': ['user']},
 u'leigh.mason': {'alias': u'Leigh Mason',
                  'connector': 'ldap',
                  'force_authuser': True,
                  'force_authuser_webservice': True,
                  'language': None,
                  'ldap_pw_last_changed': u'130741560497180049',
                  'locked': False,
                  'roles': ['user']},
 u'maani.g': {'alias': u'Maani G',
              'connector': 'ldap',
              'ldap_pw_last_changed': u'130737018642664132',
              'roles': ['user']},
 'omdadmin': {'alias': u'omdadmin',
              'force_authuser': False,
              'force_authuser_webservice': False,
              'language': None,
              'locked': False,
              'roles': ['admin']},
 u'paul.singh': {'alias': u'Paul Singh',
                 'connector': 'ldap',
                 'language': None,
                 'ldap_pw_last_changed': u'130759464741743556',
                 'locked': True,
                 'roles': ['user']},
 'rob': {'alias': u'Rob Canterbury',
         'force_authuser': False,
         'force_authuser_webservice': False,
         'language': None,
         'locked': False,
         'roles': ['admin']},
 'russell': {'alias': u'Russell Doig',
             'force_authuser': False,
             'force_authuser_webservice': False,
             'language': None,
             'locked': False,
             'roles': ['admin']},
 u'temp.user': {'alias': u'Temp User',
                'connector': 'ldap',
                'ldap_pw_last_changed': u'0',
                'roles': ['user']}}
